function S = generate_shuffled_trajectories2(X, shuffle_n)
    %_________
    %ABOUT: This function generates shuffled firing sequences based on the
    %statistics of real trajectories from network simulations.
    %
    %INPUTS:
    %   X = a matrix with real spike sequences generated by the network.
    %       The matrix is size [n,m] with n being the number of neurons in 
    %       the network, and m being the number of sequences. If a neuron
    %       did not spike in a particular sequence, it will have either a 0
    %       rank or a fractional rank halfway between the number of spiking
    %       neurons and n.
    %       This 0 / fractional rank will be shuffled as well, randomly 
    %       assigning a non-spike to a different neuron.
    %   shuffle_n = number of shuffled trajectories to generate
    %
    %OUTPUTS:
    %   S = a matrix of size [n,shuffle_n] with shuffled rank sequences. A
    %       non-spiking neuron will be denoted with a 0 rank.
    %_________
    
    
    %Generate shuffled data based on real sequences
    [~,m] = size(X);
    S = [];
    for i = 1:shuffle_n
        %randomly select a spike sequence
        s_i = randsample(m,1);
        sequence = X(:,s_i);
        %generate shuffle
        shuffle_seq = sequence(randsample(length(sequence),length(sequence)));
        %store shuffle
        S = [S, shuffle_seq]; %#ok<AGROW>
    end
end